version: '3.3'
services:
  database:
    image: 'mysql:8.4.0'
    container_name: 'database' 
    environment:
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: db
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - "./docker/dbInit:/docker-entrypoint-initdb.d"